### PR TITLE
Clean noisy entities

### PR DESCRIPTION
**Pull request by guyla**
Cleaner files: 

We manually removed some "noise" from some entities to get better classification for first/last name. The original version included some numbers and brackets that were removed as well.  Also, some problem with names that are common in the language - אני could be "Annie" - but it would increase false positives.

### CODE REVIEW

**Review by yotammanor — DISMISSED** [review]
@guyla Thanks for the contribution!

In order for us to be able to maintain a clean repo, I'd love if you could write a cleaner, more descriptive name for the PR, and a short description (one sentence - one paragraph) of the changes you introduced.

Thanks!

**Comment by guyla** [comment]
@yotammanor  @shaypal5  Please see updated comments. 

Guy

**Comment by shaypal5** [comment]
@guyla Thanks! The pull request now makes sense!

**Review by shaypal5 — APPROVED** [review]
A better version of the dictionaries, and with a clean PR explanation (after Yotam's review).

**Pull request merged**
